### PR TITLE
refactor: check that the user-defined table has 1 and only 1 primary key.

### LINKED ISSUE #123: About automatically adding the id field as the primary key.
If the user creates the model with an id for the primary key name then everything works fine.
Using a different name will result in the following error.

There is also the case that if I don't declare a primary key field, saffier automatically adds the id field as the primary key, which can be confusing for users. Perhaps for this case you could RAISE an error to remind the user to add the primary key, rather than helping the user to do it implicitly.

```py
class User(saffier.Model):
    ids = saffier.IntegerField(primary_key=True)
    is_active = saffier.BooleanField(default=False)
    created = saffier.DateTimeField(default=datetime.now, server_default=func.now())
    updated = saffier.DateTimeField(default=datetime.now, server_default=func.now(), auto_now=True)

    class Meta:
        registry = models
```

```sh
  File "/Users/hulk/miniforge3/envs/py38/lib/python3.8/site-packages/saffier/core/db/models/metaclasses.py", line 251, in __new__
    raise ImproperlyConfigured(
saffier.exceptions.ImproperlyConfigured: Cannot create model User with multiple primary keys.
```

### PR DESCRIPTION
**Pull request by vvanglro**
Close #123 .

### CODE REVIEW

**Comment by vvanglro** [comment]
I will fix the test case later.

**Comment by vvanglro** [comment]
@tarsil Ready, It's best to squash and merge.

**Comment by tarsil** [comment]
@vvanglro 61 files is a very big change even if it's because of pre-commit.

I would advise you to do incremental changes, not like this. Unfortunately this is huge to merge.

Do you want to make it smaller?

**Comment by vvanglro** [comment]
If the changes are ok, you can just select squash merge when you merge.

**Comment by tarsil** [comment]
@vvanglro squashing doesn't change the number of files changed unfortunately. Also majority the files changed have nothing to do with the goal of this PR. 

My advice would be to close the PR and open a smaller one only with the required changes

**Comment by vvanglro** [comment]
> @vvanglro squashing doesn't change the number of files changed unfortunately. Also majority the files changed have nothing to do with the goal of this PR.
> 
> My advice would be to close the PR and open a smaller one only with the required changes

Test cases cannot pass ci tests without modifications. So all file modifications are relevant to this PR.

**Comment by tarsil** [comment]
@vvanglro where changing the `.editorconfig` impacts the test cases?

**Comment by vvanglro** [comment]
> @vvanglro where changing the `.editorconfig` impacts the test cases?

Caused by running pre-commit locally, Added line breaks.

**Pull request closed without merging**
